### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by 26000** [koto-bank/komf#5]
Komf won't save a file, says this when I try to upload something:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/komf`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:189
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:206
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:469
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:376
  12: rust_begin_unwind
             at src/libstd/panicking.rs:303
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/6767d9b90b6b630ad8e2a9e5e02fd74c00c98759/src/libcore/result.rs:933
  16: komf::upload
             at src/main.rs:126
  17: core::ops::function::Fn::call
             at /rustc/6767d9b90b6b630ad8e2a9e5e02fd74c00c98759/src/libcore/ops/function.rs:69
  18: <F as iron::middleware::Handler>::handle
             at /home/26000/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.6.1/src/middleware/mod.rs:389
  19: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
             at /home/26000/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.6.1/src/middleware/mod.rs:395
  20: <mount::mount::Mount as iron::middleware::Handler>::handle
             at /home/26000/.cargo/registry/src/github.com-1ecc6299db9ec823/mount-0.4.0/src/mount.rs:122
  21: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
             at /home/26000/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.6.1/src/iron.rs:176
  22: hyper::server::Worker<H>::keep_alive_loop
             at /home/26000/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:340
  23: hyper::server::Worker<H>::handle_connection
             at /home/26000/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:282
  24: hyper::server::handle::{{closure}}
             at /home/26000/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:242
  25: hyper::server::listener::spawn_with::{{closure}}
             at /home/26000/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/listener.rs:50
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Running rustc 1.40.0-nightly (6767d9b90 2019-10-11). I tried specifying a `FILE_DIR` env var, but it didn't help, and I can't find any references to that env var in code. How is it supposed to be set? (Sorry, it's been a long time since the last time I've set it up, so I don't remember.)

It creates db.yaml file successfully though.

**Comment by vaartis** [comment]
`FILE_DIR` is actually a constant in code, [at the top of the `src/main.rs`](https://github.com/koto-bank/komf/blob/master/src/main.rs#L36). It's `files` by default.

I should probably remake this thing from scratch and do it properly.

**Comment by 26000** [comment]
Oh, so I just needed to create that directory. I thought that it might just be a hardcoded path (but expected some weird Rust magic setting it from an env var somewhere), but never actually tried to create that directory. It works now, thanks!
